name: "BaseControl Master"
description: "Control your Powerplant"
version: "0.5.8" # Git tag which will be checked out
slug: "base_control_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
uart:
  true
usb:
  true
map:
  - homeassistant_config:rw
