name: "BaseControl"
description: "Control your Powerplant"
version: "0.5.7" # Git tag which will be checked out
slug: "base_control_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
uart:
  true
usb:
  true
map:
  - addons:rw