name: "BaseControl"
description: "Control your Powerplant"
version: "0.5.0"
slug: "base_control_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
ports:
  1883/tcp: 1883
uart:
  true
usb:
  true
map:
  - addons:rw